version: '3'

services:

  ngrok:
    container_name: skynet_ngrok
    image: wernight/ngrok
    ports:
      - "4040:4040"
    links:
      - frontend
    environment:
      - NGROK_PORT=app:8100
      - NGROK_PROTOCOL=http
      - NGROK_AUTH=3fVv5QDD6Wh5jDUg7CtEg_6tsUV7Nz5gy1M6vZA7myF

  frontend:
    container_name: skynet_ai_frontend
    build: ./
    ports:
      - "8100:8100"
    volumes:
      - "./frontend:/tmp"
